esphome:
  name: test-esp32
  friendly_name: test-esp32

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

globals:
  - id: counter
    type: int
    restore_value: no
    initial_value: "0"

sensor:
  - platform: template
    name: "Counter Value"
    id: counter_sensor
    lambda: |-
      return id(counter);
    update_interval: 1s
    state_class: measurement
    unit_of_measurement: "count"
    state_topic: "tower1/sensor/temperature"

interval:
  - interval: 1s
    then:
      - lambda: |-
          id(counter) += 1;
      - component.update: counter_sensor

mqtt:
  broker: !secret mqtt_broker_ip_address
  birth_message:
    topic: esp32-status/topic
    payload: online
  will_message:
    topic: esp32-status/topic
    payload: offline

# Enable logging
logger:

ota:
  - platform: esphome
    password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Esp32 Fallback Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:

